# Generated by Django 5.1.5 on 2025-01-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProyectoServidor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
